### ISSUE TITLE
 :(

### ISSUE THREAD

**Issue by 123dma** [chapeupreto/sinesp#1]
Array ( [codigoRetorno] => 7 [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo. ) O ano do veiculo eh

**Comment by chapeupreto** [comment]
Versão atualizada!
Por favor, confirme se está ok para que eu possa fechar a issue.

**Comment by chapeupreto** [comment]
Esse tipo de problema já tinha sido reportado em outra issue, a qual já foi encerrada.
Assim, encerrando essa issue também.
