### ISSUE TITLE
Não funciona

### ISSUE THREAD

**Issue by igtoth** [chapeupreto/sinesp#10]
Já tentei usar diferentes proxies e continua: 

Com proxy:
O servidor retornou nenhuma resposta!

Sem proxy:
Array ( [codigoRetorno] => 1 [mensagemRetorno] => Erro no processamento da consulta. ) Array ( [codigoRetorno] => 1 [mensagemRetorno] => Erro no processamento da consulta. )

**Comment by chapeupreto** [comment]
Talvez exista alguma configuração com o seu ISP que esteja atrapalhando suas consultas.
Já tentou executar o seu script, por exemplo, na Amazon AWS?

**Comment by igtoth** [comment]
Meu servidor está rodando local na minha maquina, uso NET, tentei agora pela TIM e mesma coisa. 

Estou chamando sua classe (require 'sinep.php';)

```
$veiculo = new Sinesp;
$veiculo->buscar('GWW-6471');

try {

print_r($veiculo->dados());
    $veiculo->buscar('GWW-6471');
    if ($veiculo->existe()) {
        print_r($veiculo->dados());
        echo 'O ano do veiculo eh ' , $veiculo->anoModelo, PHP_EOL;
    }
} catch (\Exception $e) {
    echo $e->getMessage();
}


```

**Comment by chapeupreto** [comment]
@igtoth Criei um novo branch (`missing-xml-tags`) e fiz algumas alterações.

Tenta usar esse branch ao invés do master.

Por favor, execute o seguintes passos:

```bash
git clone https://github.com/chapeupreto/sinesp.git
cd sinesp
git checkout missing-xml-tags
composer install
```

Se tudo ok, então crie um arquivo `php` (por exemplo, `index.php`) com o mesmo contéudo disponível na seção de `Utilização` e verifique os resultados na execução do mesmo.

**Comment by igtoth** [comment]
Funciona!

**Comment by chapeupreto** [comment]
Ótimo!

Vou mergear no master então e fechar a issue!

Obrigado!
