### ISSUE TITLE
como alterar a placa digitada num form

### ISSUE THREAD

**Issue by gambiarraweb1** [chapeupreto/sinesp#12]
Ola, como eu faco para nao vir preenchido o campo `$veiculo->buscar('$AAA0000');`
pois no modelo atual a placa fica definida e nao consigo alterar, sempre...

tenho uma pagina onde precisava digitar a placa num form com outras info.. ao digitar no campo placa ele faz a consulta neste sistema acima, e preenche os demais campos do meu form que tem carro, ano e cor...

o sistema em si eu sei dar o `print_r($veiculo->dados());` para exibir os dados
mas nao conseguir implementar essa acao que mencionei...

obrigado

**Comment by chapeupreto** [comment]
Olá, 

para isso bastaria você salvar a placa que vem do seu form em uma variável e usar essa variável no método buscar.

Como não se trata de uma issue exatamente, vou fechar esse ticket.
