### ISSUE TITLE
Versão desatualizada

### ISSUE THREAD

**Issue by vjoao** [chapeupreto/sinesp#13]
Mensagem versão desatualizada, favor atualizar o aplicativo na consulta.

**Comment by EmersonHenriique** [comment]
Estou com o mesmo problema, no caso se possível ensine a pegar o $token para que nas próximas atualizações poderemos atualizar o código.

@chapeupreto

**Comment by guirociozanini** [comment]
Estou tentando descobrir como pegar o token, mas sem sucesso por enquanto.

**Comment by igtoth** [comment]
Estou com o mesmo problema... 

```
Array
(
    [codigoRetorno] => 7
    [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo.
)
```

Tem como disponibilizar o processo para pagar o novo token/chave?

**Comment by doidloko** [comment]
Decompilei o app do sinesp e achei a nova key
"PiRtabjHDFasdLmioKKt"

porém não estão gerando o hmac da mesma forma, antes era PLACA+KEY agora não sei como está mais.

Este por exemplo é um HMAC para a placa IVF4149
f3b8c242da1d46bc6b716cda4ab08b2ccfe29620

não sei como foi gerado esse código acima, ele foi gerado no app do sinesp

**Comment by guirociozanini** [comment]
Juntamos um pessoal em um chat para tentar encontrarmos a solução juntos,

https://discord.gg/fwntSWc

**Comment by igtoth** [comment]
@vjoao pode passar a soluçao pra mim? sou "Mr.T" do chat! vlw

**Comment by ocanhacom** [comment]
Alguma novidade sobre a atualizacao?

**Comment by hereck** [comment]
Pra mim ele retorna esse erro abaixo, sabe o que pode ser?

Message: O servidor retornou nenhuma resposta!

**Comment by SilvioCohen** [comment]
Pude verificar no AKP do Sinesp que tem 2 chaves:
 PiRtabjHDFgerLmioKKt
PiRtabjHDFasdLmioKKt

Alguém viu isso?

**Comment by SilvioCohen** [comment]
Pude verificar no AKP do Sinesp que tem 2 chaves:
PiRtabjHDFgerLmioKKt
PiRtabjHDFasdLmioKKt

Alguém viu isso?

**Comment by SilvioCohen** [comment]
Pude verificar no AKP do Sinesp que tem 2 chaves:
PiRtabjHDFgerLmioKKt
PiRtabjHDFasdLmioKKt

Alguém viu isso?

**Comment by DinoDoDelphi** [comment]
Pude verificar no AKP do Sinesp que tem 2 chaves:
PiRtabjHDFgerLmioKKt
PiRtabjHDFasdLmioKKt

Alguém viu isso?

**Comment by EmersonHenriique** [comment]
https://discord.gg/3shuzyT

**Comment by gpedro** [comment]
enquanto ninguém disponibiliza a solução, existe um fallback:
https://www.checkmeucarro.com.br/minha-conta/pesquisaGratis/pesquisar/?placa=IWY9888

**Comment by sandropf** [comment]
Estou com o mesmo erro.
Imagino que além de consertar a key tem que consertar a versão do app tbm:

<d>7.1.1</d>
<e>4.3.1</e>

Pelo que captei do android.manifest são esses. 
Se alguém conseguir a key publica aqui por favor.

**Comment by chapeupreto** [comment]
Atualizado para versão `1.2.0` utilizando a nova chave `Mw6HqdLgQsX41xAGZgsF` relatada pelo @ricardotominaga
