### ISSUE TITLE
O projeto parou de funcionar esse ano de 2018.

### ISSUE THREAD

**Issue by danielvianati** [chapeupreto/sinesp#14]
Aparece esse erro ao usar essas rotinas, as mesmas estavam funcionando até o final de 2017, e em 2018 parou.

{"codigoRetorno":"7","mensagemRetorno":"Versão desatualizada. Favor atualizar aplicativo."}

**Comment by evertonesm** [comment]
alguem achou uma solução?

**Comment by chapeupreto** [comment]
Atualizado para versão `1.2.0` utilizando a nova chave `Mw6HqdLgQsX41xAGZgsF` relatada pelo @ricardotominaga

**Comment by v101011** [comment]
Ainda continua dando o erro , mesmo com a chave nova , voces tem alguma idéia do que pode ser ?

**Comment by v101011** [comment]
o que fiz foram os passos simples instalei através do composer , e utilizar o script para chamar como está na pagina nada de mudança

**Comment by chapeupreto** [comment]
E qual o erro?

**Comment by danielvianati** [comment]
Esta funcionando normalmente.



Em 5 de fev de 2018 10:10 PM, "Rod Elias" <notifications@github.com>
escreveu:

**Comment by v101011** [comment]
[codigoRetorno] => 7
            [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo.

**Comment by v101011** [comment]
[codigoRetorno] => 7
            [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo.

**Comment by v101011** [comment]
esse é o codigo que recebe a placa e faz a busca

<?php
require 'vendor/autoload.php';
$postdata = file_get_contents("php://input");
$request = json_decode($postdata);
$placa = $request->placa;



use Sinesp\Sinesp;
$veiculo = new Sinesp;

$veiculo->buscar($placa);
print_r($veiculo);


?>

**Comment by v101011** [comment]
> <?php
> require 'vendor/autoload.php';
> $postdata = file_get_contents("php://input");
> $request = json_decode($postdata);
> $placa = $request->placa;
> 
> 
> 
> use Sinesp\Sinesp;
> $veiculo = new Sinesp;
> 
> $veiculo->buscar($placa);
> print_r($veiculo);
> 
> 
> ?>

**Comment by v101011** [comment]
```
<?php
require 'vendor/autoload.php';
$postdata = file_get_contents("php://input");
$request = json_decode($postdata);
$placa = $request->placa;



use Sinesp\Sinesp;
$veiculo = new Sinesp;

$veiculo->buscar($placa);
print_r($veiculo);


?>
```

**Comment by v101011** [comment]
o restante veio por aqui composer require chapeupreto/sinesp

**Comment by danielvianati** [comment]
Começou dar erro novamente essa madrugada 06/02/18.
Voltou a aparecer versão desatualizada.

**Comment by chapeupreto** [comment]
Novas alterações adicionadas na release `1.3.0`. Essa release utiliza a versão `v3` da API.

**Comment by v101011** [comment]
Agora está show , funcionando , 

pelo que entendi ele trava , pela não utilizacao do captcha , usando o captcha esse problema acabaria !? 


Obrigado

**Comment by v101011** [comment]
Pessoal . o erro voltou novamente ! 

não existe uma versao com captcha ?! 
para acabar com essas issus ?

**Comment by chapeupreto** [comment]
Funcionando normalmente.
Fique à vontade para criar um projeto que utiliza a versão com Captcha e poste no GitHub pra gente! 👍

**Comment by v101011** [comment]
Criado , vou fazer o upload no github , quer que coloque no seu ?!

**Comment by chapeupreto** [comment]
Um repo separado é melhor.
