### ISSUE TITLE
Falta executar o CURL

### ISSUE THREAD

**Issue by jpdesignerrio** [chapeupreto/sinesp#18]
No código está:
`       curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
        curl_close($ch);`

Falta o `$this->response = curl_exec($ch);` antes do curl_close($ch);

Além disso, toda placa consultada resulta em:
Array ( [codigoRetorno] => 1 [mensagemRetorno] => Erro no processamento da consulta. )

**Comment by chapeupreto** [comment]
Não entendi. A instrução que você menciona está presente na linha `76`.
Esse problema pode estar relacionado ao `proxy`. Existe uma seção sobre isso no `README`. Também verifique se seu sistema atende aos requisitos necessários. 

Lib funcionando normalmente.
