### ISSUE TITLE
o acesso deve ter sido alterado de novo pelo SERPRO

### ISSUE THREAD

**Issue by thiagoms83** [chapeupreto/sinesp#2]
php -f sample.php 
Array
(
    [codigoRetorno] => 7
    [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo.
)
O ano do veiculo eh

**Comment by chapeupreto** [comment]
Versão atualizada!
Por favor, confirme se está ok para que eu possa fechar a issue.

**Comment by thiagoms83** [comment]
100% agora.
Valeuuuu

**Comment by 123dma** [comment]
Muito bom pessoal 100%... obrigado !!!

**Comment by pedropauloportella** [comment]
Boa noite @chapeupreto poderia me explicar como faz para atualizar a API, está me retornando Array ( [codigoRetorno] => 7 [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo. ) ,'/',

Dei uma olhada nas outras issues referenciadas por você sobre o mesmo caso mas não consegui resolver nada. 
Obrigado

**Comment by chapeupreto** [comment]
@portellapedro para você atualizar a biblioteca, basta salvar o arquivo `Sinesp.php` desse repositório ou iniciar um novo projeto com `composer require chapeupreto/sinesp`.

**Comment by pedropauloportella** [comment]
Funcionou. Obrigado @chapeupreto
