### ISSUE TITLE
Informações adicionais

### ISSUE THREAD

**Issue by gustavocass** [chapeupreto/sinesp#21]
Olá, primeiramente excelente a sua API, funcionou perfeitamente!
Gostaria de saber se existe a possibilidade de adicionar 2 informações pertinentes aos veículos.
Tipo de combustível: Alcool, Gasolina, Flex, Diesel etc.
e Tipo de veiculo: Passeio, Comercia, etc.

Mais uma vez parabéns pela API.

**Comment by chapeupreto** [comment]
Olá! Fico feliz que tenha funcionado!
Entenda que essa biblioteca apenas realiza a consulta na base do `Sinesp`.
É o Sinesp que devolve as informações.
Essas informações adicionais teriam que ser implementadas do lado do Sinesp, pois não tenho controle sobre elas.
