### ISSUE TITLE
Sistema atualizado e parou de repente

### ISSUE THREAD

**Issue by bigam** [chapeupreto/sinesp#23]
Pessoal , alguém sabe o motivo do sistema parar de repente de funcionar ?

esta atualizado e estava rodando perfeitamente. 

segue o erro abaixo

"<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'O servidor retornou nenhuma resposta!' in /home/v1010375/placa.com/vendor/chapeupreto/sinesp/src/Sinesp.php:84
Stack trace:
#0 /home/v1010375/placa.com/vendor/chapeupreto/sinesp/src/Sinesp.php(49): Sinesp\Sinesp-&gt;tratarResposta()
#1 /home/v1010375/placa.com/vendor/chapeupreto/sinesp/src/Sinesp.php(22): Sinesp\Sinesp-&gt;exec()
#2 /home/v1010375/placa.com/placa.php(16): Sinesp\Sinesp-&gt;buscar('numero da placa')
#3 {main}
  thrown in <b>/home/v1010375/placa.com/vendor/chapeupreto/sinesp/src/Sinesp.php</b> on line <b>84</b><br />
"

**Comment by chapeupreto** [comment]
Sistema funcionando normalmente.

O erro que mostrou acima é porque o código da sua aplicação não está tratando a exceção disparada.

**Comment by bigam** [comment]
Parceiro , eu nao sei dizer a razao mas o problema está no server ! testei em outro server e foi 100% 
vou analisar melhor o server com erro e atualizo aqui o que pode ser !
