### ISSUE TITLE
Usando código default - O servidor retornou nenhuma resposta!

### ISSUE THREAD

**Issue by bigam** [chapeupreto/sinesp#24]
{data: "O servidor retornou nenhuma resposta![]↵", status: 200, headers: ƒ, config: {…}, statusText: "OK"}

expandido 

{data: "O servidor retornou nenhuma resposta![]↵", status: 200, headers: ƒ, config: {…}, statusText: "OK"}
config
:
{method: "POST", transformRequest: Array(1), transformResponse: Array(1), paramSerializer: ƒ, jsonpCallbackParam: "callback", …}
data
:
"O servidor retornou nenhuma resposta![]↵"
headers
:
ƒ (i)
status
:
200
statusText
:
"OK"
__proto__
:
Object

**Comment by erickmff** [comment]
Aqui ta normal

**Comment by chapeupreto** [comment]
Operando normal.

**Comment by bigam** [comment]
Usando o proxy ele funcionou e parou do nada , estou seguindo sua idéia de configurar um EC2 para testar depois retorno !

**Comment by chapeupreto** [comment]
O proxy é pago? Porque pode ser que o proxy que você está usando tenha parado de funcionar.

**Comment by viniciusmelocodes** [comment]
Essa lista me ajudou
http://spys.one/free-proxy-list/BR/

Na 4ª tentativa consegui êxito.
