### ISSUE TITLE
Versão desatualizada

### ISSUE THREAD

**Issue by whande1992** [chapeupreto/sinesp#25]
Esta retornando essa mensagem ao consultar uma placa:

> Array ( [codigoRetorno] => 7 [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo. ) A non-numeric value encountered

**Comment by EmersonHenriique** [comment]
Para melhor comunicação https://discord.gg/3shuzyT

**Comment by danielvianati** [comment]
Aqui tbm está dando Versão desatualizada. Alguém tem a nova secret key? grato

**Comment by whande1992** [comment]
o pessoal esta tentando la no grupo..mas ainda nada.

**Comment by danielvianati** [comment]
O pessoal no grupo conseguiu a atualização da chave?

**Comment by chapeupreto** [comment]
Liberada versão `1.5.0`
