### ISSUE TITLE
API retorna: "Versão desatualizada. Favor atualizar aplicativo."

### ISSUE THREAD

**Issue by arivanbastos** [chapeupreto/sinesp#27]
API está retornando esse erro. Creio que o atributo $secret esteja obsoleto ou o SINESP tenha implantado outro tipo de validação para evitar consultas de sistemas externos.

**Comment by giovanigenerali** [comment]
@arivanbastos já tentou atualizar conforme https://github.com/chapeupreto/sinesp/commit/af2c65e2d6b106e2345eb0b2b18934977517de45 ?

**Comment by arivanbastos** [comment]
@giovanigenerali caramba, vocês são rápidos! :-) 👍 
Desculpe a falta de atenção, atualizei e funcionou!
Obrigado!
