### ISSUE TITLE
API parou de funcionar 28-08-2018

### ISSUE THREAD

**Issue by danielvianati** [chapeupreto/sinesp#30]
API começou a parar de funcionar no final desde domingo. Alguém mais com esse problema? será se é a secret key novamente? a api de vcs estão funcionando corretamente?

**Comment by giovanigenerali** [comment]
está normal pra mim até o momento, uso proxy!

Giovani Generali

**Comment by chapeupreto** [comment]
Funcionando normalmente.

**Comment by danielvianati** [comment]
Aqui uso proxy tbm, está demorando a resposta e não traz as informações

**Comment by danielvianati** [comment]
estava funcionando normal até sábado, não mexemos em nada
vou verificar novamente o que pode estar acontecendo

**Comment by giovanigenerali** [comment]
Tenta usar uma lista de proxies, coloca um timeout se falhar pula para o próximo. dependendo do horário a consulta sofre instabilidades, normal isso.
https://www.proxynova.com/proxy-server-list/country-br/

Exemplo que utilizo internamente:
![screen shot 2018-08-28 at 11 25 38](https://user-images.githubusercontent.com/41435/44729410-21f05080-aab5-11e8-9724-2154c6289332.png)

**Comment by lucazin** [comment]
Pessoal

Uma pergunta , é contra lei ou algum crime usar esse tipo de informacao do sinesp no meu sistema ? tipo essa api em php, tem alguma restricao ?
