### ISSUE TITLE
Placas Mercosul

### ISSUE THREAD

**Issue by jpdesignerrio** [chapeupreto/sinesp#31]
O novo padrão de placas já está sendo usado no Rio de Janeiro, e já preciso fazer a validação delas. 
O modelo segue o padrão LLL NL NN para carros e LLL NN LN para motos, onde L é letra e N é número.

Ignorei a função validar($placa), que o preg_match não bate, retornando true nela manualmente. Aí recebo o erro "Erro no processamento da consulta". Alguma ajuda?

**Comment by giovanigenerali** [comment]
Acredito que nem a API do SINESP está apta para esse padrão novo. Testei no app oficial deles e só valida padrão antigo ainda.

**Comment by lucazin** [comment]
Troca a letra por numero

 A – 0; B – 1; C – 2; D – 3; E – 4; F – 5; G – 6; H – 7; I – 8; J – 9;

Seja feliz.. 


Agora uma pergunta , é contra lei ou algum crime usar esse tipo de informacao do sinesp no meu sistema ? tipo essa api em php

**Comment by jpdesignerrio** [comment]
Caramba, como não pensei nisso? haha E olha que eu já tinha visto essa associação de letras e números. E não, não é contra a lei porque é uma base de informações públicas, de um serviço público, porém sem uma forma de acesso oficial.

**Comment by lucazin** [comment]
Então se eu usar isso no meu sistema de uma maneira que nao fique exposta apenas no backend para validações não é ilegal.

A base é pública ?  isso é veridico ?

vlww
