### ISSUE TITLE
Sem retorno

### ISSUE THREAD

**Issue by dpaulabh** [chapeupreto/sinesp#33]
Bom dia. 

Estou tentando utilizar a API. Estava tudo bem. Versão 4. Agora somente fica sempre sem retorno. Vocês estão conseguindo utilizar? Mudou alguma coisa?

Segue arquivo PHP que estou utilizando. 
[Sinesp.zip](https://github.com/chapeupreto/sinesp/files/2487106/Sinesp.zip)

O link que estou utilizando 

http://www.usisoft.com.br/SUPORTE/SINESP.PHP

**Comment by chapeupreto** [comment]
Funcionando normalmente. Sugiro testar usando `proxy`.

O método de instalação foi o da documentação mesmo, isto é, `composer require chapeupreto/sinesp`
