### ISSUE TITLE
O servidor retornou nenhuma resposta!

### ISSUE THREAD

**Issue by gledsoneduardo** [chapeupreto/sinesp#35]
Boa tarde!

Primeiro: parabéns pela API!
Meu problema: rodando localmente (IP do Brasil) funciona perfeitamente com qualquer proxy da lista https://www.proxynova.com/proxy-server-list/country-br , funciona sem proxy e funciona com o proxy de exemplo, porém quando uso a aplicação no servidor da Digital Ocean (IP dos EUA) o servidor retorna sempre "O servidor retornou nenhuma resposta!" independente do proxy que eu use ( testei vários) e sem proxy retorna "Limite de consultas excedido. Tente novamente mais tarde." após pouco mais de uma centena de consultas
Me parece que o proxy não está funcionando, alguma dica?

**Comment by chapeupreto** [comment]
Vou fechar a issue então por não se tratar exatamente de um problema com a lib.
Acredito que talvez você vai precisar de um proxy mais elaborado.
Dá uma olhada em `https://kingproxies.com/`.
Existe algumas soluções pagas que talvez possam te ajudar a resolver esse problema.
