### ISSUE TITLE
Qual Versão do PHP devo utilizar ?> > > Então agora pra quem usava com PHP não tem mais solução ?

### ISSUE THREAD

**Issue by GralakCobra** [chapeupreto/sinesp#40]
> > > Então agora pra quem usava com PHP não tem mais solução ?
> > 
> > 
> > Você já conseguiu fazer funcionar em PHP?
> > Se precisar eu fiz um fork, não tenho problemas em te passar.
> 
> Eu não consegui ainda se vc puder ajudar.
> Passe o Link para eu fazer o download dele em PHP obrigado memso

Fiz o convite para você poder baixar meu repositório, não vou deixar público pois é apenas uma versão de teste, mas como você precisa vai te servir.
Fiz o favor de adicionar novas funções como a geração de Token a cada vez que a requisição falhar.
Minhas recomendações são: capturar requisição de registro para que tu tenha um ID único e possa gerar Tokens unicamente em seu sistema, adicionar um proxy (está no index.php, tem uma linha comentada com '//' se você retira-lá poderá adicionar um proxy sem ele, se hospedado em sites pode a requisição não funcionar, tem que ser um IP casual *brasileiro* (ainda estudando a natureza certa do IP).
Para consultar é necessário alterar o documento mas o meio de pesquisa pode ser alterado usando por exemplo um framework como o Slim por exemplo para a criação de uma API REST, ou até mesmo usando uma variável trazendo o valor GET, seria mais ou menos como "$placa  = $_GET['placa']" e passando a placa como index.php?placa=GGG-9996...
Há algumas coisas que precisam de melhorias mas não tenho tempo para investir nessa lib pois não é para a linguagem da qual eu faço uso, fiz algumas melhorias para lhe ajudar e não posso mais investir tanto tempo nela, as melhorias deverão ser percebidas e corrigidas, mas eu testei e está funcionado tudo muito bem.

_Originally posted by @jeffduarte97 in https://github.com/chapeupreto/sinesp/issues/37#issuecomment-510073587_

**Comment by chapeupreto** [comment]
Fechando, pois já tem uma issue (#37) que trata desse problema.
