### ISSUE TITLE
> Boa Tarde Pessoal alguém conseguiu implementar em PHP para compartilhar conosco ?

### ISSUE THREAD

**Issue by thiMoreira** [chapeupreto/sinesp#41]
> Boa Tarde Pessoal alguém conseguiu implementar em PHP para compartilhar conosco ?

O processo é fácil mas voce tem que implementar, vou postar o passo  a passo
 
 1  Etapa  - registrando o aplicativo no cloud via api
                 POST /checkin HTTP/1.1
		Host: android.clients.google.com  
		Host: android.clients.google.com
		content-length: 70
		Connection: keep-alive
		cache-control: no-cache

		{
		"userSerialNumber": 0, 
		"checkin":
		{
			"type": 1 
		},
		"version": 49
		}
       
   
2   Etapa  - gerando o token firebase 

POST /c2dm/register3 HTTP/1.1
Host: android.clients.google.com
Authorization: AidLogin 4110676151848553255:2997152737904869802
app: br.gov.sinesp.cidadao.android 
Host: android.clients.google.com 

sender=905942954488&app=br.gov.sinesp.cidadao.android&device=4110676151848553255&app_ver=49&X-appid=eFMtyJXP3459&X-subtype=905942954488&X-app_ver=49&cert=daf1d792d60867c52e39c238d9f178c42f35dd98

3 Etapa - fazendo a consulta.
  Lembra de pegar  a secreta "#8.1.0#0KnlVSWHxOih3zKXBWlo" e fazer o hash_hmac

POST /sinesp-cidadao/mobile/consultar-placa/v5 HTTP/1.1
Host: cidadao.sinesp.gov.br
Authorization: Token eFMtyJXP3459:APA91bENYracfIE0WduGFhfBeSDqzZ7V77NJbIsz374cbidjAuuLDRyGlFm3rvXwN8NrbYK1Cb_9V5djo_bsmsTblysyBiIxxrSqzLKf-A38S-_93kGU34Cyw0w5SYkvxZI8pdJ6eUJh
Content-Type: text/xml  
Host: cidadao.sinesp.gov.br
cookie: JSESSIONID=UMeSkul4N14lAm9UK35DNRxg.cidadao1; cw_aplicacao_cidadao=1.cidadao1; cw_aplicacao_mandado=1.cidadao1; cw_aplicacao_desaparecidos=1.cidadao1
accept-encoding: gzip, deflate
content-length: 617
Connection: keep-alive
cache-control: no-cache

<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
    <v:Envelope xmlns:v="http://schemas.xmlsoap.org/soap/envelope/">
    <v:Header>
    <b>samsung GT-I9192</b>
    <c>ANDROID</c>
    <d>8.1.0</d>
    <e>5.1</e>
    <f>192.168.0.11</f>
    <g>1d25306ef40c954de17356916447159e751deac8</g>
    <h>0.0</h>
    <i>0.0</i>
    <k></k>
    <l>16-07-2019 14:05:37</l>
    <m>8797e74f0d6eb7b1ff3dc114d4aa12d3</m>
    <n>eFMtyJXP3459</n>
    </v:Header>
    <v:Body>
    <n0:getStatus xmlns:n0="http://soap.ws.placa.service.sinesp.serpro.gov.br/">
    <a>PJP2356</a>
    </n0:getStatus>
    </v:Body>
    </v:Envelope>

_Originally posted by @maycon1038 in https://github.com/chapeupreto/sinesp/issues/37#issuecomment-515715692_

**Comment by thiMoreira** [comment]
Você disse os passos, mas não disse onde conseguir gerar as informações correspondentes. Não seria melhor já colocar a biblioteca atualizada? Ou explicar melhor como e onde fazer cada passo a passo. Obrigado

**Comment by chapeupreto** [comment]
Fechando, pois já tem uma issue (#37) que trata desse problema.
