### ISSUE TITLE
Ainda com o problema de "app desatualizado"

### ISSUE THREAD

**Issue by ghost** [chapeupreto/sinesp#43]
A lib PHP tá retornando isso:

Array ( [codigoRetorno] => 7 [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo. )

**Comment by HugoMiguel85** [comment]
Acompanhando, retornando mesmo erro aqui.

**Comment by chapeupreto** [comment]
Fechando, pois já tem uma issue (#37) que trata desse problema.
