### ISSUE TITLE
Atualização quebrou a api :(

### ISSUE THREAD

**Issue by 123dma** [chapeupreto/sinesp#5]
Tá retornando o código 

{"codigoRetorno":"7","mensagemRetorno":"Vers\u00e3o desatualizada. Favor atualizar aplicativo."}

**Comment by chapeupreto** [comment]
Graças à contribuição do @luciocorrea foi possível corrigir o problema.

**Comment by pedropauloportella** [comment]
Olá amigos, parece que a nossa API caiu de novo, está me retornando Array ( [codigoRetorno] => 7 [mensagemRetorno] => Versão desatualizada. Favor atualizar aplicativo. ) ,'/',

dei uma olhada nas outras issues referenciadas aqui e não consegui resolver o problema, alguma dica?
