### ISSUE TITLE
Problemas com a Atualização do Sinesp

### ISSUE THREAD

**Issue by alexandremac** [chapeupreto/sinesp#6]
Amigo, provavelmente o sinesp atualizou algo para a sua API parar de funcionar....
Será que consegue descobrir a diferença e atualiza-la?

Comecei a utilizar sua API recentemente e agora parou...

Aproveitando o comentário....
O que é a variavel $secret ?
Onde você a cadastra ou altera...

Obrigado desde já...
Ótimo trabalho.

**Comment by chapeupreto** [comment]
Fechado devido já existir uma issue aberta #5 relatando esse problema.

O secret está definido na linha 5 do arquivo `Sinesp.php`
