### ISSUE TITLE
Parou de funcionar ?

### ISSUE THREAD

**Issue by elciocf** [chapeupreto/sinesp#7]
Ocorreu alguma alteração ?
Aqui não está mais funcionando :(

**Comment by chapeupreto** [comment]
Acabei de testar e está ok.
Você está usando proxy? Confira https://github.com/chapeupreto/sinesp#proxy

**Comment by elciocf** [comment]
Não estou utilizando proxy ... estava normal até hj de manhã .. fiz algumas consultas mas agora parou 
Será que existe algum bloqueio se eu fizer mais de 10 consultas ?

**Comment by chapeupreto** [comment]
Acredito que deve haver algum bloqueio sim se a quantidade de consultas diárias for muito grande para um mesmo IP.

Para testar, tenta usando `proxy` ou mesmo outro dia.

**Comment by elciocf** [comment]
Blza vou verificar ... valeus

**Comment by chapeupreto** [comment]
Avisa se deu certo pra gente poder fechar o ticket por favor.

**Comment by elciocf** [comment]
serviço okay ... bloqueou por que consultei d+ rsrsrsr
