### ISSUE TITLE
Funcionando ainda?

### ISSUE THREAD

**Issue by arthurfolco** [chapeupreto/sinesp#8]
Aqui não está rolando, o projeto parou? rs

**Comment by chapeupreto** [comment]
Funcionando normalmente.
Qual o problema?

**Comment by astolf** [comment]
aqui esta dando um erro...

[codigoRetorno] => 1
[mensagemRetorno] => Erro no processamento da consulta

**Comment by chapeupreto** [comment]
Tenta rodar o código em uma instância EC2 da Amazon AWS. Talvez seja necessário usar proxy.

**Comment by chapeupreto** [comment]
Como não houve retorno e testes realizados apresentaram resultados ok, a issue será fechada.

**Comment by chapeupreto** [comment]
@arthurfolco @astolf 

Criei um novo branch (`missing-xml-tags`) e fiz algumas alterações.

Tenta usar esse branch ao invés do master.

Por favor, execute o seguintes passos:

```bash
git clone https://github.com/chapeupreto/sinesp.git
cd sinesp
git checkout missing-xml-tags
composer install
```

Se tudo ok, então crie um arquivo php (por exemplo, index.php) com o mesmo contéudo disponível na seção de `Utilização` e verifique os resultados na execução do mesmo.
