### ISSUE TITLE
ERRO AO CONSULTAR

### ISSUE THREAD

**Issue by MayronRaifur** [chapeupreto/sinesp#9]
Boa tarde, não estou conseguindo efetuar as pesquisas está dando o seguinte erro 

**O servidor retornou nenhuma resposta!**

alguém consegue me ajudar?

**Comment by Lukaum** [comment]
Aqui também, retorna "Erro no processamento da consulta".

**Comment by chapeupreto** [comment]
Às vezes esse problema pode ocorrer por conta do servidor de hospedagem onde o script está sendo executado. Para contornar essa restrição, sugiro tentar usar proxy ou executar o script em algum outro servidor, como por exemplo, Amazon AWS. De preferência, que o servidor esteja em algum datacenter no Brasil.

**Comment by clodoaldoevangelista** [comment]
Parabéns! Excelente script. Roda até no localhost. Tem como pegar o número do chassi completo?

**Comment by chapeupreto** [comment]
@clodoaldoevangelista Não, pois o Sinesp já devolve a informação daquele jeito, ou seja, incompleta.

Que bom que funcionou. Se puder, depois dá um *star* no projeto.

**Comment by chapeupreto** [comment]
@Lukaum @MayronRaifur 

Criei um novo branch (`missing-xml-tags`) e fiz algumas alterações.

Tenta usar esse branch ao invés do master.

Por favor, execute o seguintes passos:

```bash
git clone https://github.com/chapeupreto/sinesp.git
cd sinesp
git checkout missing-xml-tags
composer install
```

Se tudo ok, então crie um arquivo php (por exemplo, index.php) com o mesmo contéudo disponível na seção de `Utilização` e verifique os resultados na execução do mesmo.
